spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:15432/inductie_db

spring.datasource.username=dev_user
spring.datasource.password=SecurePassword123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true